# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaPictures' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  pod 'ReachabilitySwift'

  # Pods for NasaPictures

  target 'NasaPicturesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NasaPicturesUITests' do
    # Pods for testing
  end

end
